linters:
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
  HexLength:
    enabled: true
  HexNotation:
    enabled: true
  IdSelector:
    enabled: true
  ImportPath:
    enabled: true
  ImportantRule:
    enabled: true
  Indentation:
    enabled: true
    character: tab
    width: 1
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: true
  PropertySortOrder:
    enabled: true
  QualifyingElement:
    enabled: true
  SelectorDepth:
    enabled: true
  SelectorFormat:
    enabled: false
  Shorthand:
    enabled: false
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
  VendorPrefix:
    enabled: true
  ZeroUnit:
    enabled: true
